
name: Deploy do To-Do App para o Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-e-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wesleyveberpavilaki/todo-app:latest
          
  deploy-azure:
    runs-on: ubuntu-latest
    needs: build-e-push # Só faz deploy se a imagem foi publicada com sucesso

    steps:
      # Passo 1: Baixa o código (necessário para a action da Azure)
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Faz o deploy da imagem do Docker Hub no Azure App Service
      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          # Troque pelo nome do seu App Service no portal Azure
          app-name: 'wesleytodo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'wesleyveberpavilaki/todo-app'
          

          
